### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by netmiller** [andrey-p/markdown-it-classy#3]
Is it possible to allow also dot like syntax :

```
This is paragraph 2 and I wish there was a way to make it blue.
{.blue}
```

it might be a little bit more logical and does not confuse with some template languages?

**Comment by andrey-p** [comment]
@netmiller I've considered that, but I'm afraid I'll stick with the current syntax for the time being. Hope you don't mind if I go into quite a bit of detail about it. A similar question has been asked before and I'm sure it'll be asked again.

I'm aware there's currently [discussion on the CommonMark forum](http://talk.commonmark.org/t/consistent-attribute-syntax/272) about a standardised way of specifying attributes - a few people seem to have implemented it already, but nothing seems to be set in stone yet. 

I can definitely see the use of being able to specify attributes, but it's probably not the best approach for this plugin. I haven't built it with scalability in mind - as it is, adding in other attributes would probably be a massive performance and complexity problem, and will require a lot of further planning.

Plus, it seems that the `markdown-it` devs are [already considering it](https://github.com/markdown-it/markdown-it/issues/34) so I'd like to avoid the duplication of effort.

To finally answer your question - adding a dot syntax will create an illusion that I'm trying to create a more complete plugin for adding attributes, which I'd like to stay clear of for the reasons above - at least for the time being.

> does not confuse with some template languages

That's a good point. I'm not sure if I've seen a template language that uses a single curly bracket (`{ }`) for templating - Handlebars and other Mustache-like languages use double curly brackets (`{{ }}`), and I may have seen template engines that use e.g. `{: }`. `markdown-it-classy` should only parse single curly brackets containing characters you'd see in a class string: alphanumeric characters, dash, underscore and space. I think that should reduce the possibility of a conflict.

Hope that clears things up a bit, and sorry about the wall of text! :)

**Comment by netmiller** [comment]
On 16.2.2015, at 19.22, Andrey Pissantchev notifications@github.com wrote:

> does not confuse with some template languages
> 
> That's a good point. I'm not sure if I've seen a template language that uses a single curly bracket ({ }) for templating - Handlebars and other Mustache-like languages use double curly brackets ({{ }}), and I may have seen template engines that use e.g. {: }. markdown-it-classy should only parse single curly brackets containing characters you'd see in a class string: alphanumeric characters, dash, underscore and space. I think that should reduce the possibility of a conflict.
> 
> Hope that clears things up a bit, and sorry about the wall of text! :)

Hi Andrey, that’s ok for me, not problem.  It’s better to wait for a while to see what is happening.

I’m using heavily Jade-template, and that was my background for this.
Jade has quite similar syntax [variation] :
- var title = "On Dogs: Man's Best Friend";
- var author = "enlore";
- var theGreat = "<span>escape!</span>";
  h1= title
  p Written with love by #{author}
  p This will be safe: #{theGreat}

and maintaining jade-templates and markdown docs at same project is sometimes [when you are tired] confusing.

Thank’s for your clear answer, now I see you have considered this and I trust it better to see what is happening.

/Esa Laitila
